apiVersion: apps/v1
kind: Deployment
metadata:
  name: fenrir-backend
  labels:
    sourabh: {{ .Values.num }}
spec:
  selector:
    matchLabels:
      app: fenrir-backend
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: fenrir-backend
    spec:
      containers:
      - name: fenrir-backend
        image: docker.io/talhaabdurrahman/fenrir-backend
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_HOST
          value: mongo.fenrir.svc.cluster.local
--- 
apiVersion: v1
kind: Service
metadata:
  name: fenrir-backend
spec:
  selector:
    app: fenrir-backend
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer

